name: BentoBox-Visit
main: world.bentobox.visit.VisitPladdon
version: ${project.version}${build.number}
api-version: "1.17"

authors: [BONNe]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
